.libPaths(c("/usr/local/lib/R/site-library", .libPaths()))

suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(wrapr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(testit))
suppressPackageStartupMessages(library(doParallel))
suppressPackageStartupMessages(library(foreach))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(STEAM))


######################### Read in arguments #########################

option_list <- list( 
  make_option(c("-v", "--verbose"), action="store_true", default=TRUE,
              help="Print extra output [default]"),
  make_option(c("-q", "--quietly"), action="store_false", 
              dest="verbose", help="Print little output"),
  make_option(c("-i", "--inputFile"),
              help="admixmap.txt output from admixMap2.R"),
  make_option(c("-O", "--outDir"), default = getwd(), help = "output directory"),
  make_option(c("-o", "--outName"), help = "output prefix"),
  make_option(c("-g", "--globalAncestry"), 
              help="global ancestry results generated by getGlobalAnc.R"),
  make_option(c("-G", "--generations"), default = 8,
              help="Number of generations since admixture began.  Should use same value as used in RFmix, but it ultimately has little effect"),
  make_option(c("-r", "--reps"), default = 10000,
              help="Number of reps for threshold simulations.")
)

opt <- parse_args(OptionParser(option_list=option_list))

dat = read.table(opt$inputFile, header = T)
anc = read.table(opt$globalAncestry, header = T)

dat %<>% mutate(cM = (sgpos + egpos) / 2, chr = chm) %>% select(cM, chr) 
anc %<>% select(-sample)

thresh = get_thresh_simstat(g = opt$generations, map = dat, props = anc, nreps = opt$reps)
